# simulate data to use in evaluations/illustrations
library(optparse)    # for terminal options
library(genio)       # to write BED files for external software
library(simgenphen)  # for genotype+phenotype simulations

# a name for temporary BED/etc data, under project dir
name <- 'data'

############
### ARGV ###
############

# define options
option_list = list(
    make_option(c("-n", "--n_ind"), type = "integer", default = 1000, 
                help = "number of individuals", metavar = "int"),
    make_option(c("-m", "--m_loci"), type = "integer", default = 10000, 
                help = "number of loci", metavar = "int"),
    make_option(c("-k", "--k_subpops"), type = "integer", default = 3, 
                help = "admixture intermediate subpopulations", metavar = "int"),
    make_option(c("-f", "--fst"), type = "double", default = 0.3, 
                help = "FST (fixation index)", metavar = "double"),
    make_option(c("--bias_coeff"), type = "double", default = 0.5, 
                help = "admixture bias coeff", metavar = "double"),
    make_option(c("-g", "--generations"), type = "integer", default = 1, 
                help = "number of generations, for realistic local kinship", metavar = "int"),
    make_option("--herit", type = "double", default = 0.8, 
                help = "heritability", metavar = "double"),
    make_option("--m_causal", type = "integer", default = 100, 
                help = "num causal loci", metavar = "int"),
    make_option("--fes", action = "store_true", default = FALSE, 
                help = "Use FES instead of RC trait model")
)

opt_parser <- OptionParser(option_list = option_list)
opt <- parse_args(opt_parser)

# get values
n_ind <- opt$n_ind
m_loci <- opt$m_loci
k_subpops <- opt$k_subpops
fst <- opt$fst
bias_coeff <- opt$bias_coeff
G <- opt$generations
m_causal <- opt$m_causal
herit <- opt$herit
fes <- opt$fes


# output path for BED files and all results files
dir_out <- paste0(
    'sim-admix',
    '-n', n_ind,
    '-m', m_loci,
    '-k', k_subpops,
    '-f', fst,
    '-s', bias_coeff,
    '-mc', m_causal,
    '-h', herit,
    '-g', G,
    if ( fes ) '-fes' else '-rc'
)

# go where we want data outputs to be
setwd( '../data' )

# place data in a new figure specific to this simulation
if ( !dir.exists( dir_out ) )
    dir.create( dir_out )
setwd( dir_out )


############
### SIMS ###
############

# simulate genotypes and trait as usual
data <- sim_gen_phen(
    n_ind = n_ind,
    m_loci = m_loci,
    m_causal = m_causal,
    k_subpops = k_subpops,
    bias_coeff = bias_coeff,
    G = G,
    herit = herit,
    fes = fes,
    fst = fst
)
X <- data$X
kinship_true <- data$kinship
trait <- data$trait
causal_indexes <- data$causal_indexes
causal_coeffs <- data$causal_coeffs

# save causal trait data for AUC evaluations later
save(
    trait,
    causal_indexes,
    causal_coeffs,
    file = 'simtrait.RData'
)

# write BED version for external code
plink_data <- write_plink(name, X, pheno = trait)
fam <- plink_data$fam # copy FAM autogenerated by write_plink
# write phenotype file
write_phen(name, fam)

# put all kinship matrices in a subdirectory
dir.create( 'kinship' )
setwd( 'kinship' )

# write true kinship matrix in format and scale that GCTA expects
# NOTE: there's no "fam" and "M" here, we'll create it in next script to match that of estimates
write_grm( 'true', 2 * kinship_true )
