# simulate data to use in evaluations/illustrations
library(optparse)    # for terminal options
library(genio)       # to write BED files for external software
library(simgenphen)  # for genotype+phenotype simulations

# a name for temporary BED/etc data, under project dir
name <- 'data'

############
### ARGV ###
############

# define options
option_list = list(
    make_option(c("-n", "--n_ind"), type = "integer", default = 1000, 
                help = "number of individuals", metavar = "int"),
    make_option(c("-m", "--m_loci"), type = "integer", default = 10000, 
                help = "number of loci", metavar = "int"),
    make_option(c("-k", "--k_subpops"), type = "integer", default = 3, 
                help = "admixture intermediate subpopulations", metavar = "int"),
    make_option(c("-f", "--fst"), type = "double", default = 0.3, 
                help = "FST (fixation index)", metavar = "double"),
    make_option(c("--bias_coeff"), type = "double", default = 0.5, 
                help = "admixture bias coeff", metavar = "double"),
    make_option(c("-g", "--generations"), type = "integer", default = 1, 
                help = "number of generations, for realistic local kinship", metavar = "int"),
    make_option("--herit", type = "double", default = 0.8, 
                help = "heritability", metavar = "double"),
    make_option("--fes", action = "store_true", default = FALSE, 
                help = "Use FES instead of RC trait model"),
    make_option(c("-r", "--rep"), type = "integer", default = 1, 
                help = "Replicate number", metavar = "int")
)

opt_parser <- OptionParser(option_list = option_list)
opt <- parse_args(opt_parser)

# get values
n_ind <- opt$n_ind
m_loci <- opt$m_loci
k_subpops <- opt$k_subpops
fst <- opt$fst
bias_coeff <- opt$bias_coeff
G <- opt$generations
herit <- opt$herit
fes <- opt$fes
rep <- opt$rep

# output path for BED files and all results files
# let's have main path describe genotypes but not phenotypes (i.e. no herit) as one genotype sim can have multiple phenotypes
dir_out <- paste0(
    'sim-admix',
    '-n', n_ind,
    '-m', m_loci,
    '-k', k_subpops,
    '-f', fst,
    '-s', bias_coeff,
    '-g', G
)

# go where we want data outputs to be
setwd( '../data' )

# place data in a new dir specific to this simulation
# may exist already because we repeat for each replicate separately
if ( !dir.exists( dir_out ) )
    dir.create( dir_out )
setwd( dir_out )

# lastly, create replicate subdirectory
# never overwrite existing replicates!
dir_rep <- paste0( 'rep-', rep )
if ( dir.exists( dir_rep ) )
    stop( 'Replicate ', rep, ' already exists!' )
dir.create( dir_rep )
setwd( dir_rep )

############
### SIMS ###
############

# always set m_causal automatically using the other variables, as done for pca-assoc project
# for default n,h values it equals the previous default m_causal too!
m_causal <- round( n_ind * herit / 8 )
message( 'm_causal: ', m_causal )

# simulate genotypes and trait as usual
data <- sim_gen_phen(
    n_ind = n_ind,
    m_loci = m_loci,
    m_causal = m_causal,
    k_subpops = k_subpops,
    bias_coeff = bias_coeff,
    G = G,
    herit = herit,
    fes = fes,
    fst = fst
)
X <- data$X
kinship_true <- data$kinship
trait <- data$trait
causal_indexes <- data$causal_indexes
causal_coeffs <- data$causal_coeffs
p_anc <- data$p_anc # NEW!  (not saved for original sim in preprint!)

######################
### SAVE GENOTYPES ###
######################

# write BED version for external code
# NOTE: it contains trait of first simulation run, but we ought to ignore it always!
plink_data <- write_plink(name, X, pheno = trait)
# write p_anc in same location
save( p_anc, file = 'p_anc.RData' )

# put all kinship matrices in a subdirectory
dir.create( 'kinship' )
# write true kinship matrix in format and scale that GCTA expects
# NOTE: there's no "fam" and "M" here, we'll create it in next script to match that of estimates
write_grm( 'kinship/true', 2 * kinship_true )

######################
### SAVE PHENOTYPE ###
######################

# create and move into new directory if heritability is non-default
if ( herit != 0.8 ) {
    dir_out <- paste0( 'h-', herit )
    if ( !dir.exists( dir_out ) )
        dir.create( dir_out )
    setwd( dir_out )
}
# now let's save the remaining files in this new location

fam <- plink_data$fam # copy FAM autogenerated by write_plink
# write phenotype file
write_phen(name, fam)

# save causal trait data for AUC evaluations later
save(
    trait,
    causal_indexes,
    causal_coeffs,
    file = 'simtrait.RData'
)


